### DISCUSSION TITLE
Autogain and severe overshoot when adding a new stream.

### DISCUSSION THREAD

**Discussion by ak2766** [wwmm/easyeffects#3639] [General]
# First, I love EasyEffects.  Thanks for making this fantastic and feature rich audio equalizer that makes my Linux desktop really awesome - 💖.

# TL;DR
I believe your answer @ https://github.com/wwmm/easyeffects/discussions/2477#discussioncomment-6608457 is the right path to follow to resolve this issue, but please read on as I having one question at the end.

# Now the problem
PS: _this was all before I had seen your previous answer regarding the compressor effect_ and felt that removing it all might be a disservice to others with a similar concern.

I normally have my music streaming from either Rhythmbox or Radio Garden.  I normally set the volume for both quite low - the one below is from Radio Garden:

![Selection_00137](https://github.com/user-attachments/assets/e425ab1f-b3dd-436a-8986-b0d36446fbc6)

## Main Problem:
If I happen to launch a YouTube video, **_the initial YouTube audio is too loud and distorted before autogain kicks in and lowers it_**.  What I'm after is - low audio volume from my music stream (Radio Garden here) and loud(er) audio volume for the YouTube video (somewhat like pipe music in a restaurant):

![Selection_00138](https://github.com/user-attachments/assets/da0d4713-cbee-47ad-b0b8-1754513e15cb)

What can I do to limit this overshoot from happening?  I'm sometimes using a headset and that really hurts my puny ear drums.

## OS: Ubuntu 24.04.1 (fully patched)
```
$ > sudo apt update 2>/dev/null | grep upgradable && apt list --upgradable && phased
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
Listing... Done
grub-common/noble-updates 2.12-1ubuntu7.1 amd64 [upgradable from: 2.12-1ubuntu7]
grub-efi-amd64-bin/noble-updates 2.12-1ubuntu7.1 amd64 [upgradable from: 2.12-1ubuntu7]
grub-efi-amd64-signed/noble-updates 1.202.2+2.12-1ubuntu7.1 amd64 [upgradable from: 1.202+2.12-1ubuntu7]
grub-efi-amd64/noble-updates 2.12-1ubuntu7.1 amd64 [upgradable from: 2.12-1ubuntu7]
grub-emu/noble-updates 2.12-1ubuntu7.1 amd64 [upgradable from: 2.12-1ubuntu7]
grub2-common/noble-updates 2.12-1ubuntu7.1 amd64 [upgradable from: 2.12-1ubuntu7]
Listing...
grub-common
     2.12-1ubuntu7.1 500 (phased 39%)
grub-efi-amd64-bin
     2.12-1ubuntu7.1 500 (phased 39%)
grub-efi-amd64-signed
     1.202.2+2.12-1ubuntu7.1 500 (phased 39%)
grub-efi-amd64
     2.12-1ubuntu7.1 500 (phased 39%)
grub-emu
     2.12-1ubuntu7.1 500 (phased 39%)
grub2-common
     2.12-1ubuntu7.1 500 (phased 39%)
```

## Laptop Audio:
```
Audio:
  Device-1: Intel Alder Lake PCH-P High Definition Audio
    driver: sof-audio-pci-intel-tgl
  Device-2: NVIDIA driver: snd_hda_intel
  Device-3: Logitech C920 HD Pro Webcam driver: snd-usb-audio,uvcvideo
    type: USB
  Device-4: Lenovo ThinkPad Thunderbolt 4 Dock USB Audio
    driver: hid-generic,snd-usb-audio,usbhid type: USB
  API: ALSA v: k6.8.0-51-lowlatency status: kernel-api
  Server-1: PipeWire v: 1.0.5 status: active
```
## Autogain setting 1 stream (Only the Radio Garden audio stream is currently playing):
![Selection_00139](https://github.com/user-attachments/assets/887bd008-074d-4a5f-a894-f52456264087)

## Autogain setting 2 streams (with both Garden Radio and YouTube):
![Selection_00140](https://github.com/user-attachments/assets/18491431-114a-43d7-9c0f-7f59fd3c320f)

## Potential Solution:
Your answer @ https://github.com/wwmm/easyeffects/discussions/2477#discussioncomment-6608457 appears to be what I'm after - the `compressor` effect.  However, when I turn it on, it ramps up the other stream too soon - meaning that small pauses in the YouTube video cause my Radio Garden audio stream to ramp back up leading to these very annoying periodic gain overshoots.  In fact, I'd say they intrude more than that initial overshoot when it isn't turned on!

## Compressor settings:
![Selection_00141](https://github.com/user-attachments/assets/ec602d74-93b7-4719-9e7f-4ce2bd9bc095)
