### ISSUE TITLE
PulseEffects 4.8.7 Flatpak: Recieved update broke LoudnessEqualizerPE preset

### ISSUE THREAD

**Issue by RagglenLove** [wwmm/easyeffects#2284]
### EasyEffects Version

PulseEffects 4.8.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Xubuntu 20.04

### Describe the bug

On April 19, 2023, I received an update from Flathub, here's the log report:

```
flatpak remote-info --log flathub com.github.wwmm.pulseeffects

PulseEffects - Audio Effects for PulseAudio Applications

        ID: com.github.wwmm.pulseeffects
       Ref: app/com.github.wwmm.pulseeffects/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 4.8.7
   License: GPL-3.0
Collection: org.flathub.Stable
  Download: 9.2 MB
 Installed: 31.0 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08

       Sdk: org.freedesktop.Sdk/x86_64/22.08
    Commit: 6f937e08360792958a3b75a27fadf35f8a600fb731a597795d8ab018b0e7cd53
    Parent: d095efb34d274ce7675b3a6a595eb3aa72cdf25570127e9cd14d380346c72c4b
   Subject: chore: Add .flatpak to .gitignore (b47663e1)
      Date: 2023-04-19 19:55:02 +0000
   History: 
```

This update has broken the LoudnessEqualizerPE.json that I've been using for a number of years now. Here's a link to the preset: [github.com/Digitalone1/EasyEffects-Presets/blob/master/LoudnessEqualizerPE.json](https://github.com/Digitalone1/EasyEffects-Presets/blob/master/LoudnessEqualizerPE.json)

As a test, I've downgraded PulseEffects to the previous update that is dated on June 24, 2022, here's the log and command I used to downgrade:

```
    Commit: d095efb34d274ce7675b3a6a595eb3aa72cdf25570127e9cd14d380346c72c4b
   Subject: 21.08 (#63) (5de3a484)
      Date: 2022-06-24 02:37:17 +0000

sudo flatpak update --commit=d095efb34d274ce7675b3a6a595eb3aa72cdf25570127e9cd14d380346c72c4b com.github.wwmm.pulseeffects
```

After downgrading, my LoudnessEqualizerPE preset works again.

I've locked this version of PulseEffects with this command:

`sudo flatpak mask com.github.wwmm.pulseeffects`

I'll be staying on the previous version for now, until this is fixed, thanks.

### Expected Behavior

LoudnessEqualizerPE preset should fix audio that is too low.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>
