### ISSUE TITLE
Documentation/manual in github pages?

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#2310]
I think it would be nice to add the documentation to github pages.

It turns out it is easy to export the mallard doc pages by running (install `yelp-tools` for `yelp-build`):

```
mkdir help/html
yelp-build html -o help/html help/C
```

Then the html directory contains web page files with a `index.html` and can be uploaded to github pages using an action (you don't need to maintain a seperate branch).

<details>
<summary>Generic action example</summary>
<br>

```yaml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
```

</details>

A website was discussed in #770, but this is only another place for the help pages to make them more accessible. It is easier to click a documentation link on the readme then to open the app and then click the manual button (which I feel is easy to miss if not paying attention). Also you can read it without needing to install the yelp package.

It may be smart to put the version in the help page itself (maybe in the about section?), and only run the deploy workflow on pushes to tags, so the documentation github page will always show the latest version, but not unreleased changes.
